# Generated by Django 5.0.2 on 2024-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
