# Generated by Django 5.0.2 on 2024-03-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_comment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
